controller_manager:
  ros__parameters:
    update_rate: 50  # Hz (Adjust as needed)

    driveline_controller:
      type: "main_computer_urc/DriveTrainManager"

driveline_controller:
  ros__parameters:
    joints:
      - lf_wheel_joint
      - lm_wheel_joint
      - lb_wheel_joint
      - rf_wheel_joint
      - rm_wheel_joint
      - rb_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position
