name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    
    - name: Build the Docker image
      run: ./softwareUpdate/dockerBuild.sh 
